### ISSUE TITLE
How should we log or print regular expressions?

### ISSUE THREAD

**Issue by pulkitsinghal** [ShoppinPal/sp-json-logger#5]
This `console.log('query', query);` logs an object with a regular expression inside it and it is accurately reflected in the logs as: `query { sku: /^BA1262$/i }`

But if we use `sp-json-logger`:
`logger.debug( { log: { query: query } } );` 
or:
`logger.debug( { log: { query: JSON.stringify(query) } } );`
it produces:
`"log":{"query":"{\"sku\":{}}"}`
which is misleading!

How should we prepare to log such objects so we can get the expected string printed out?

**Comment by pulkitsinghal** [comment]
@yogesh8177 - can you take a look at this?

**Comment by yogesh8177** [comment]
For the time being we can do logger.debug( { log: { query: query.toString() } } );
It gives output as: `"log":{"sku":"/^BA1262$/i"}`

**Comment by yogesh8177** [comment]
I created a branch `feature/regex-support` for it. Let me know if it helps @pulkitsinghal.

See: https://github.com/ShoppinPal/sp-json-logger/pull/6

**Comment by pulkitsinghal** [comment]
Tried it out, it all works, thanks
